apiVersion: v1
kind: Service
metadata:
   name: nginx
   labels:
     app: nginx
spec:
   type: LoadBalancer
   ports:
     - protocol: TCP
       port: 80
       targetPort: 80
   selector:
     app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx 
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: arichards98/nginx:latest
        ports:
          - containerPort: 80